name: Mailgen Workflow

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests faker  # Add any other required dependencies

      - name: Run Mailgen script
        run: python mailgen/mailgen.py -n 100 -o emails.txt
