name: Mailgen Workflow

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # We need the full history for this approach

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests faker  # Add any other required dependencies

      - name: Run Mailgen script
        run: python mailgen/mailgen.py -n 100 -o emails.txt

      - name: Commit and force push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add emails.txt
          git commit -m "Update generated emails"
          git fetch origin main
          git checkout -B temp-branch
          git reset --soft origin/main
          git add .
          git commit -m "Update generated emails"
          git push --force origin temp-branch:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-emails
          path: emails.txt
