name: Mailgen Workflow

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests faker  # Add any other required dependencies

      - name: Run Mailgen script
        run: python mailgen.py -n 100 -o emails.txt

      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add emails.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update generated emails" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-emails
          path: emails.txt
